[project]
name = "bonet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clickhouse-connect>=0.10.0",
    "pandas>=2.3.3",
    "pymssql>=2.3.11",
    "tabulate>=0.9.0",
]
